// remote-react/src/components/Button.tsx
import { useCountStore } from "../store/useCount";

function Button() {
  const count = useCountStore((state) => state.count);
  const increaseCount = useCountStore((state) => state.increaseCount);

  return (
    <>
      <p>React Component</p>
      <button type="button" onClick={() => increaseCount()}>
        count is {count}
      </button>
    </>
  );
}

export default Button;

// layout/src/components/Button.vue
<script setup lang="ts">
import { useCountStore } from "../store/zustandCount";

const count = useCountStore((state) => state.count);
const increaseCount = useCountStore((state) => state.increaseCount);

const add = () => increaseCount();
</script>

<template>
  <div class="card">
    <button type="button" @click="add">count is {{ count }}</button>
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
