// remote/src/components/Button.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);

const add = () => count.value++;
</script>

<template>
  <div class="card-vue">
    <img src="../assets/vue.svg" class="logo vue" alt="Vue logo" />
    <button type="button" @click="add">count is {{ count }}</button>
  </div>
</template>

<style scoped>
.card-vue {
  margin: 10px;
  padding: 2em;
  border: 1px solid #4fc08d;
  border-radius: 5px;
  font-size: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
}
</style>

// remote-svelte/src/lib/Button.svelte
<script lang="ts">
  import svelteLogo from '../assets/svelte.svg'
  
  let count: number = $state(0)
  const increment = () => {
    count += 1
  }
</script>

<div class="svelte-card">
  <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
  <button onclick={increment}>
    count is {count}
  </button>
</div>

<style>
  .svelte-card {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    border: 1px solid #ff3e00;
    border-radius: 5px;
    padding: 10px;
    margin: 10px;
  }
</style>
